import { useEffect, useMemo, useReducer, useRef, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, CheckCircle2, Clock3, GitBranch, Globe2, LockKeyhole, RotateCcw, Search, ShieldCheck, Users, Wallet } from 'lucide-react';
import { CycleGraph, Modal } from './ui';
import { LanguageContext, dictionaries, type Language } from './i18n';
import { DEMO_STORAGE, demoLegs, demoManifest, demoMatches, demoMints, demoOffers, demoPeople, demoReducer, restoreDemo, type DemoAction, type DemoSize } from './demo-state';

const languageAtStart = (): Language => {
  const query = new URLSearchParams(location.search).get('lang');
  if (query === 'en' || query === 'pl') return query;
  try { return localStorage.getItem('swapcircle:language') === 'en' ? 'en' : 'pl'; } catch { return 'pl'; }
};
const stateAtStart = () => { try { return restoreDemo(sessionStorage.getItem(DEMO_STORAGE)); } catch { return restoreDemo(null); } };

export function DemoApp() {
  const [language, setLanguage] = useState<Language>(languageAtStart);
  const [state, dispatch] = useReducer(demoReducer, undefined, stateAtStart);
  const [confirmation, setConfirmation] = useState<DemoAction | null>(null);
  const [consent, setConsent] = useState(false);
  const heading = useRef<HTMLHeadingElement>(null);
  const actionApplied = useRef(false);
  const d = (pl: string, en: string) => language === 'pl' ? pl : en;
  const offers = demoOffers(state.size);
  const matches = useMemo(() => demoMatches(state), [state.size, state.excluded]);
  const legs = useMemo(() => demoLegs(state), [state.size, state.excluded]);
  const inOffers = state.stage === 'offers';
  const inMatches = state.stage === 'matches';
  const hasCycle = !inOffers && !inMatches;
  const settled = state.stage === 'settled';
  const expired = state.stage === 'expired' || state.stage === 'refunded';
  const terminal = settled || state.stage === 'refunded';
  const step = inOffers ? 0 : inMatches ? 1 : terminal ? 3 : 2;
  const names = demoPeople.slice(0, state.size);
  const token = (mint: string) => demoMints.find(m => m.mint === mint)?.symbol || mint;
  const person = confirmation && 'participant' in confirmation ? confirmation.participant : 0;
  const currentOffer = offers[person]?.payload;
  const finalDeposit = confirmation?.type === 'fund' && state.funded.length === state.size - 1;
  const change = (action: DemoAction) => { actionApplied.current = !!confirmation; dispatch(action); setConfirmation(null); };
  const confirm = (action: DemoAction) => { actionApplied.current = false; setConsent(false); setConfirmation(action); };
  const switchLanguage = () => {
    const next = language === 'pl' ? 'en' : 'pl';
    const url = new URL(location.href);
    url.searchParams.set('lang', next);
    history.replaceState(history.state, '', url);
    setLanguage(next);
  };
  const title = inOffers ? d('Każdy szuka czegoś innego.', 'Everyone wants something different.')
    : inMatches ? (matches.cycles.length ? d('Te oferty tworzą pełny cykl.', 'These offers complete the circle.') : d('Te oferty nie tworzą pełnego cyklu.', 'These offers do not complete a circle.'))
    : settled ? d('Każdy otrzymał to, czego chciał.', 'Everyone received what they wanted.')
    : state.stage === 'refunded' ? (state.funded.length ? d('Depozyty wróciły do właścicieli.', 'Deposits are back with their owners.') : d('Cykl zamknięty bez wpłat.', 'Circle closed without deposits.'))
    : expired ? d('Termin minął. Odbierz swój depozyt.', 'Time is up. Recover your deposit.')
    : d('Wpłacajcie niezależnie.', 'Deposit independently.');
  const subtitle = inOffers ? d('Alicja, Bartek i Celina chcą wymienić tokeny. SwapCircle łączy ich oferty w wymianę, której nie da się zawrzeć w parach.', 'Alicja, Bartek and Celina want to exchange tokens. SwapCircle connects offers into an exchange that direct pairs cannot complete.')
    : inMatches ? d('Algorytm sprawdził dokładne tokeny i ilości. Strzałki pokazują, do kogo trafi każda wpłata.', 'The matcher checked the exact tokens and amounts. The arrows show where each deposit goes.')
    : settled ? d('Ostatnia wpłata rozliczyła wszystkie przekazania jednocześnie. Pozostałe osoby nie musiały niczego podpisywać ponownie.', 'The final deposit settled every transfer together. The other participants did not need to sign again.')
    : expired ? d('Niedokończona wymiana nie przenosi tokenów do kontrahentów. Każdy odzyskuje własną wpłatę bez zgody innych osób.', 'An incomplete exchange does not transfer tokens to counterparties. Each person recovers their own deposit without anyone else’s approval.')
    : d('Pierwsze wpłaty czekają w skarbcach. Ostatnia poprawna wpłata uruchomi całą wymianę w jednej transakcji.', 'Early deposits wait in vaults. The final valid deposit completes the whole exchange in one transaction.');

  useEffect(() => {
    document.documentElement.lang = language;
    document.title = `${title} | SwapCircle Demo`;
    try { localStorage.setItem('swapcircle:language', language); } catch { /* Optional preference. */ }
  }, [language, title]);
  useEffect(() => { try { sessionStorage.setItem(DEMO_STORAGE, JSON.stringify(state)); } catch { /* Demo still works without browser storage. */ } }, [state]);

  return <LanguageContext.Provider value={language}><div className="demo-app">
    <a className="skip-link" href="#main-content" onClick={event => { event.preventDefault(); heading.current?.focus(); }}>{d('Przejdź do treści', 'Skip to content')}</a>
    <header className="demo-header"><a href="?mode=demo" className="brand" aria-label="SwapCircle"><span className="brand-icon"><GitBranch size={24} /></span>SwapCircle<span className="brand-dot">.</span></a><span className="demo-badge">Demo</span><div className="demo-header-actions"><button className="language-button" aria-label={d('Switch to English', 'Przełącz na polski')} onClick={switchLanguage}><Globe2 size={16} />{language.toUpperCase()}</button><button className="button button-secondary" onClick={() => change({ type: 'reset' })}><RotateCcw size={15} />{d('Od początku', 'Start over')}</button></div></header>
    <main id="main-content" className="demo-main">
      <nav className="demo-steps" aria-label={d('Etapy wymiany', 'Exchange steps')}>{[d('Oferty', 'Offers'), d('Dopasowanie', 'Match'), d('Wpłaty', 'Deposits'), d('Wynik', 'Outcome')].map((name, i) => <span key={i} className={`${step === i ? 'current' : ''} ${step > i ? 'complete' : ''}`} aria-current={step === i ? 'step' : undefined}><b>{step > i ? <Check size={14} /> : `0${i + 1}`}</b>{name}{i < 3 ? <ArrowRight size={15} /> : null}</span>)}</nav>

      <section className={`demo-intro ${terminal ? 'demo-intro-complete' : ''}`}><div><div className="eyebrow"><span />{d('WYMIANA TOKENÓW BEZ POWIERNIKA', 'TOKEN EXCHANGE WITHOUT A CUSTODIAN')}</div><h1 ref={heading} tabIndex={-1} data-testid="demo-title">{title}</h1><p>{inOffers && state.size !== 3 ? d(`${state.size} osoby, dokładne warunki i wspólna wymiana. Sprawdź, jak oferty łączą się w cykl.`, `${state.size} participants, exact terms and one exchange. Explore how their offers form a circle.`) : subtitle}</p></div><div className="demo-intro-mark" aria-hidden="true">{terminal ? <CheckCircle2 /> : expired ? <ShieldCheck /> : <GitBranch />}</div></section>

      {inOffers ? <>
        <div className="section-heading demo-board-heading"><div><h2>{d('Tablica ofert', 'Offer board')}</h2><p>{d('Wybierz oferty i znajdź zgodną wymianę.', 'Select offers and find a compatible exchange.')}</p></div><fieldset className="demo-sizes"><legend>{d('Liczba osób', 'Participants')}</legend>{([2, 3, 4] as DemoSize[]).map(size => <button key={size} className={state.size === size ? 'selected' : ''} aria-pressed={state.size === size} onClick={() => change({ type: 'reset', size })}>{size}</button>)}</fieldset></div>
        <div className={`offer-grid demo-offers demo-count-${state.size}`}>{offers.map(({ payload: offer }, i) => <article className={`offer-card ${state.excluded.includes(i) ? 'demo-offer-excluded' : ''}`} key={offer.owner} data-testid={`offer-${i}`}><div className="offer-top"><span className={`avatar avatar-${i}`}>{names[i].name[0]}</span><div><strong>{names[i].name}</strong><small>{d('Oferta w społeczności', 'Community offer')}</small></div><label className="demo-offer-select"><input type="checkbox" checked={!state.excluded.includes(i)} onChange={() => change({ type: 'toggle', participant: i })} aria-label={d(`Uwzględnij ofertę: ${names[i].name}`, `Include offer: ${names[i].name}`)} /></label></div><div className="offer-amount"><small>{d('Oddaje', 'Gives')}</small><div><strong>{offer.giveAmount}</strong><span className={`token-symbol token-${i}`}>{token(offer.giveMint)}</span></div></div><div className="offer-divider"><ArrowDown size={16} /></div><div className="offer-amount"><small>{d('Chce otrzymać', 'Wants')}</small><div><strong>{offer.wantAmount}</strong><span className="token-symbol">{token(offer.wantMint)}</span></div></div><div className="offer-footer"><span><Clock3 size={14} />{d('Dokładna ilość', 'Exact amount')}</span><span>{d('Tokeny demo', 'Demo tokens')}</span></div></article>)}</div>
        <div className="demo-callout"><div><GitBranch size={23} /><div><strong>{state.size === 2 ? d('Dwie strony mogą wymienić się bezpośrednio.', 'Two participants can exchange directly.') : d('Żadna para nie spełnia obu potrzeb.', 'No pair satisfies both participants.')}</strong><p>{state.size === 2 ? d('Te same zasady wpłat i zwrotu działają także dla pary.', 'The same deposit and refund rules also work for a pair.') : d('Cykl pozwala połączyć wszystkie oferty w jedną wymianę.', 'A circle can connect all of these offers into one exchange.')}</p></div></div><button className="button button-primary" data-testid="find-cycle" onClick={() => change({ type: 'search' })}><Search size={17} />{d('Znajdź wymianę', 'Find an exchange')}<ArrowRight size={16} /></button></div>
      </> : null}

      {inMatches ? <>
        <div className="demo-metrics"><div><strong>{matches.scope.searchedOffers}</strong><span>{d('sprawdzone oferty', 'offers checked')}</span></div><div><strong>{matches.scope.pairCycles}</strong><span>{d('zgodne pary', 'compatible pairs')}</span></div><div className="accent"><strong>{matches.scope.cyclesFound}</strong><span>{d('pełny cykl', 'complete circle')}</span></div></div>
        {matches.cycles.length ? <section className="panel demo-match-panel"><div className="section-heading"><h2>{d('Każda oferta ma odbiorcę', 'Every offer has a recipient')}</h2><span className="badge badge-green"><Users size={14} />{state.size} {d('osoby', 'participants')}</span></div><CycleGraph legs={legs} manifest={demoManifest} copy={dictionaries[language]} showAddresses={false} /><div className="demo-match-actions"><button className="text-button" onClick={() => change({ type: 'back' })}>{d('Wróć do ofert', 'Back to offers')}</button><button className="button button-primary" data-testid="create-cycle" onClick={() => confirm({ type: 'create' })}>{d('Utwórz cykl', 'Create circle')}<ArrowRight size={16} /></button></div></section> : <div className="panel empty"><Search size={30} /><h2>{d('Przywróć brakującą ofertę', 'Restore the missing offer')}</h2><p>{d('Wymiana wymaga zgodnego odbiorcy dla każdej oferty. Wróć do tablicy i ponownie zaznacz wszystkie osoby.', 'Every offer needs a compatible recipient. Return to the board and select all participants again.')}</p><button className="button button-primary" onClick={() => change({ type: 'back' })}>{d('Wróć do ofert', 'Back to offers')}</button></div>}
      </> : null}

      {hasCycle ? <>
        <div className={`demo-cycle-status ${expired ? 'demo-status-expired' : ''}`} role="status" aria-live="polite"><div>{settled ? <CheckCircle2 size={22} /> : expired ? <ShieldCheck size={22} /> : <LockKeyhole size={22} />}<div><strong data-testid="cycle-state">{settled ? d('Wymiana rozliczona', 'Exchange settled') : state.stage === 'refunded' ? (state.funded.length ? d('Wszystkie depozyty zwrócone', 'All deposits refunded') : d('Brak depozytów do zwrotu', 'No deposits to refund')) : expired ? d('Zwroty dostępne', 'Refunds available') : d(`${state.funded.length} z ${state.size} wpłat`, `${state.funded.length} of ${state.size} deposits`)}</strong><p>{settled ? d('Wszystkie przekazania w ostatniej wpłacie', 'All transfers executed with the final deposit') : expired ? d('Każdy depozyt można odzyskać oddzielnie', 'Every deposit can be recovered separately') : d('Tokeny oczekują na komplet wpłat', 'Tokens wait for all deposits')}</p></div></div><div className="demo-clock"><Clock3 size={17} /><div><strong>{expired ? '00:00' : '02:00'}</strong><small>{d('zegar demo', 'demo clock')}</small></div>{state.stage === 'funding' ? <button className="button button-secondary" data-testid="expire-cycle" onClick={() => confirm({ type: 'expire' })}>{d('Pokaż upływ terminu', 'Advance to deadline')}</button> : null}</div></div>
        <div className={`demo-deposit-grid demo-count-${state.size}`}>{offers.map(({ payload: offer }, i) => {
          const deposited = state.funded.includes(i), refunded = state.refunded.includes(i);
          return <article className={`demo-deposit-card ${settled || refunded ? 'demo-card-done' : deposited ? 'demo-card-funded' : ''}`} key={offer.owner} data-testid={`deposit-${i}`}><div className="offer-top"><span className={`avatar avatar-${i}`}>{names[i].name[0]}</span><div><strong>{names[i].name}</strong><small>{settled ? d('Wymiana zakończona', 'Exchange complete') : refunded ? d('Depozyt zwrócony', 'Deposit refunded') : deposited ? d('Depozyt wpłacony', 'Deposit made') : expired ? d('Bez depozytu', 'No deposit') : d('Czeka na wpłatę', 'Awaiting deposit')}</small></div>{settled || refunded ? <CheckCircle2 className="accent" size={20} /> : deposited ? <LockKeyhole className="accent" size={19} /> : null}</div><div className="demo-transfer"><span>{d('Wpłata', 'Deposit')}</span><strong>{offer.giveAmount} <small>{token(offer.giveMint)}</small></strong><ArrowDown size={17} /><span>{settled ? d('Otrzymano', 'Received') : expired ? d('Planowany odbiór', 'Planned receipt') : d('Do otrzymania', 'To receive')}</span><strong>{offer.wantAmount} <small>{token(offer.wantMint)}</small></strong></div>{state.stage === 'funding' && !deposited ? <button className="button button-primary" data-testid={`fund-${i}`} onClick={() => confirm({ type: 'fund', participant: i })}><Wallet size={15} />{d(`Wpłać jako ${names[i].name}`, `Deposit as ${names[i].name}`)}</button> : state.stage === 'expired' && deposited && !refunded ? <button className="button button-primary" data-testid={`refund-${i}`} onClick={() => confirm({ type: 'refund', participant: i })}><ShieldCheck size={16} />{d(`Odbierz ${offer.giveAmount} ${token(offer.giveMint)}`, `Recover ${offer.giveAmount} ${token(offer.giveMint)}`)}</button> : <div className="demo-card-outcome">{settled ? <><Check size={16} />{d(`Otrzymano ${offer.wantAmount} ${token(offer.wantMint)}`, `Received ${offer.wantAmount} ${token(offer.wantMint)}`)}</> : refunded ? <><Check size={16} />{d(`Odzyskano ${offer.giveAmount} ${token(offer.giveMint)}`, `Recovered ${offer.giveAmount} ${token(offer.giveMint)}`)}</> : deposited ? d('Czeka na pozostałe osoby', 'Waiting for other participants') : d('Brak środków do zwrotu', 'No funds to refund')}</div>}</article>;
        })}</div>

        <section className="panel demo-balances"><div className="section-heading"><div><h2>{d('Co dzieje się z tokenami?', 'Where are the tokens?')}</h2><p>{d('Stan portfeli i skarbców w tym scenariuszu.', 'Wallet and vault balances in this scenario.')}</p></div><span className="badge badge-neutral">Demo</span></div><div className="table-wrap"><table><caption className="sr-only">{d('Salda uczestników', 'Participant balances')}</caption><thead><tr><th>{d('Osoba', 'Participant')}</th><th>{d('W portfelu', 'In wallet')}</th><th>{d('W skarbcu', 'In vault')}</th><th>{d('Otrzymane z wymiany', 'Received in exchange')}</th></tr></thead><tbody>{offers.map(({ payload: offer }, i) => { const held = state.funded.includes(i) && !state.refunded.includes(i) && !settled; const own = !state.funded.includes(i) || state.refunded.includes(i); return <tr key={i} data-testid={`balance-${i}`}><td><strong>{names[i].name}</strong></td><td>{own ? offer.giveAmount : '0'} {token(offer.giveMint)}</td><td>{held ? offer.giveAmount : '0'} {token(offer.giveMint)}</td><td className={settled ? 'accent' : ''}>{settled ? offer.wantAmount : '0'} {token(offer.wantMint)}</td></tr>; })}</tbody></table></div></section>

        {terminal ? <div className="demo-callout demo-next"><div><ShieldCheck size={25} /><div><strong>{settled ? d('A jeśli jedna osoba nie wpłaci?', 'What if someone never deposits?') : d('Sprawdź także udaną wymianę.', 'Try a successful exchange too.')}</strong><p>{settled ? d('Uruchom drugi cykl, wpłać jako dwie osoby i przejdź do terminu zwrotu.', 'Start another circle, deposit as two participants and advance to the refund deadline.') : d('Utwórz cykl i wykonaj wszystkie wpłaty w dowolnej kolejności.', 'Create a circle and make all deposits in any order.')}</p></div></div><button className="button button-primary" data-testid="try-again" onClick={() => change({ type: 'reset' })}>{d('Wypróbuj drugi scenariusz', 'Try the other scenario')}<ArrowRight size={16} /></button></div> : null}
        <details className="panel demo-details"><summary>{d('Przebieg cyklu i uzgodnione przekazania', 'Circle history and agreed transfers')}</summary><ol className="demo-history">{state.events.map((event, i) => <li key={i}><span>{String(i + 1).padStart(2, '0')}</span>{event.kind === 'created' ? d('Zapisano uczestników, kwoty i termin.', 'Participants, amounts and deadline recorded.') : event.kind === 'settled' ? d('Ostatnia wpłata wykonała wszystkie przekazania.', 'The final deposit executed every transfer.') : event.kind === 'expired' ? d('Termin minął. Nowe wpłaty są zamknięte.', 'The deadline passed. Deposits are closed.') : event.kind === 'funded' ? d(`${names[event.participant!].name}: depozyt trafił do skarbca.`, `${names[event.participant!].name}: deposit entered the vault.`) : d(`${names[event.participant!].name}: własny depozyt wrócił do portfela.`, `${names[event.participant!].name}: original deposit returned to their wallet.`)}</li>)}</ol><CycleGraph legs={legs} manifest={demoManifest} copy={dictionaries[language]} showAddresses={false} /></details>
      </> : null}

      <div className="demo-principles"><div><GitBranch size={21} /><strong>{d('Dopasowanie 2–4 osób', 'Match 2–4 participants')}</strong><p>{d('Dokładne tokeny i ilości z ofert.', 'Exact tokens and amounts from offers.')}</p></div><div><LockKeyhole size={21} /><strong>{d('Wszystko w ostatniej wpłacie', 'Everything in the final deposit')}</strong><p>{d('Pełna wymiana albo zwrot po terminie.', 'Complete exchange or refund after the deadline.')}</p></div><div><ShieldCheck size={21} /><strong>{d('Własny depozyt, własny zwrot', 'Your deposit, your refund')}</strong><p>{d('Bez zgody kontrahentów i operatora.', 'No approval from counterparties or operator.')}</p></div></div>
      <footer className="page-footer demo-footer"><span>{d('Interaktywna symulacja · tokeny demonstracyjne', 'Interactive simulation · demo tokens')}</span><a href="./watch.html">{d('Film i prezentacja', 'Video and presentation')}<ArrowUpRight size={13} /></a><a href="?mode=app#/board">{d('Klient Solana', 'Solana client')}<ArrowUpRight size={13} /></a><span>DEFOZO SOFTWARE HOUSE</span></footer>
    </main>

    <Modal onCloseFocus={() => { if (!actionApplied.current) return false; heading.current?.focus({ preventScroll: true }); return true; }} open={confirmation !== null} setOpen={open => { if (!open) setConfirmation(null); }} title={confirmation?.type === 'create' ? d('Warunki wspólnej wymiany', 'Terms of the exchange') : confirmation?.type === 'expire' ? d('Przejdź do terminu zwrotu', 'Advance to the refund deadline') : confirmation?.type === 'refund' ? d(`Zwrot dla: ${names[person]?.name}`, `Refund for: ${names[person]?.name}`) : d(`Wpłata: ${names[person]?.name}`, `Deposit: ${names[person]?.name}`)} description={d('Interaktywne demo. Zatwierdzenie zmienia stan tego scenariusza.', 'Interactive demo. Confirming changes this scenario’s state.')}>
      {confirmation?.type === 'create' ? <><div className="demo-confirm-terms">{offers.map(({ payload: offer }, i) => <div key={i}><strong>{names[i].name}</strong><span>{offer.giveAmount} {token(offer.giveMint)} <ArrowRight size={14} /> {offer.wantAmount} {token(offer.wantMint)}</span></div>)}</div><div className="notice"><Clock3 size={19} /><div><strong>{d('Termin: 2 minuty zegara demo', 'Deadline: 2 minutes on the demo clock')}</strong><p>{d('Depozyt pozostaje zablokowany do rozliczenia lub zwrotu po terminie. Zegar przesuniesz przyciskiem w widoku cyklu.', 'A deposit stays locked until settlement or refund after the deadline. Advance the clock using the button in the circle view.')}</p></div></div></> : confirmation?.type === 'expire' ? <div className="notice"><Clock3 size={20} /><p>{d('W tym scenariuszu czas przejdzie do ustalonego terminu. Nowe wpłaty zostaną zamknięte. Każda wpłacająca osoba będzie mogła osobno odzyskać swój depozyt.', 'The scenario clock will advance to the agreed deadline. New deposits will close. Each depositor will be able to recover their own deposit independently.')}</p></div> : currentOffer ? <><div className="demo-confirm-amount"><span>{confirmation?.type === 'refund' ? d('Do Twojego portfela', 'Back to your wallet') : d('Twój depozyt', 'Your deposit')}</span><strong>{currentOffer.giveAmount} {token(currentOffer.giveMint)}</strong></div><div className="notice"><ShieldCheck size={20} /><p>{confirmation?.type === 'refund' ? d('Tokeny wrócą wyłącznie do pierwotnego właściciela depozytu. Pozostałe osoby nie muszą być dostępne ani zatwierdzać zwrotu.', 'Tokens return only to the original depositor. Other participants do not need to be online or approve the refund.') : finalDeposit ? d('To ostatnia wpłata. Wszystkie uzgodnione przekazania wykonają się razem z nią, bez kolejnego zatwierdzenia przez pozostałe osoby.', 'This is the final deposit. Every agreed transfer will execute with it, without another approval from the other participants.') : d('Tokeny będą czekać w skarbcu. Wymiana wykona się po ostatniej wpłacie. Jeśli zabraknie uczestnika, odzyskasz depozyt po terminie.', 'Tokens will wait in the vault. The final deposit completes the exchange. If someone is missing, you can recover your deposit after the deadline.')}</p></div></> : null}
      {confirmation?.type === 'create' || confirmation?.type === 'fund' ? <label className="demo-consent"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} />{d('Akceptuję ilości, odbiorców i blokadę depozytu do rozliczenia albo terminu zwrotu.', 'I accept the amounts, recipients and deposit lock until settlement or the refund deadline.')}</label> : null}
      <div className="modal-actions"><button className="button button-secondary" onClick={() => setConfirmation(null)}>{d('Anuluj', 'Cancel')}</button><button className="button button-primary" data-testid="confirm-demo-action" disabled={(confirmation?.type === 'create' || confirmation?.type === 'fund') && !consent} onClick={() => { if (confirmation) change(confirmation); }}>{confirmation?.type === 'create' ? d('Utwórz cykl', 'Create circle') : confirmation?.type === 'expire' ? d('Przejdź do terminu', 'Advance to deadline') : confirmation?.type === 'refund' ? d('Odbierz depozyt', 'Recover deposit') : finalDeposit ? d('Wpłać i rozlicz wymianę', 'Deposit and settle exchange') : d('Zatwierdź wpłatę', 'Confirm deposit')}<ArrowRight size={15} /></button></div>
    </Modal>
  </div></LanguageContext.Provider>;
}
